services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-snippet
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    command: npm run start

  api-test:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-snippet
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
    - mongo
    command: npm run test

volumes:
  mongo_data:
