version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-snippet
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    command: sh -c "npm run test && exec npm run start"

volumes:
  mongo_data:
